### PR TITLE
Add ADFS support for mobile applications

### LINKED ISSUE #269: Support for ADFS
I am creating a PR in case others are interested in this functionality. I am seeing @defano also mentions a similar request in #254, but for Gov Cloud; my PR to resolve this issue should cover both.

### PR DESCRIPTION
**Pull request by AndreasHassing**
Closes #269, and potentially #254 as well (@defano to confirm).

### CODE REVIEW

**Review by dban-msft — APPROVED** [review]

**Review by josemiguelvarela — APPROVED** [review]
>Thank you @AndreasHassing

**Comment by miaritisnestor1986** [comment]
Hi, maybe this is not the best place to add my question... Anyway i get the accessToken successfully but when i try to call my .net 7 web api i get 401 unauthorized. I have done all the configuration in my .net project correctly. Is there anyone with the same problem? The exception i get is this:  IDX20803: Unable to obtain configuration from: 'https://login.live.com/oauth20_desktop.srf/<my-tenant-id>/v2.0/.well-known/openid-configuration'. Will retry at '29/1/2024 12:31:26 PM +00:00'. Exception: 'System.Text.Json.JsonException: IDX10805: Error deserializing json: '' into 'Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration'. Can anyone help me?

**Comment by AndreasHassing** [comment]
@miaritisnestor1986 can you show us your AD FS app config and also the auth Config?

**Comment by miaritisnestor1986** [comment]
Solved! I changed the scope from the mobile app and replace login.live.com with login.microsoftonline.com. Thankx :)

**Pull request merged**
