### PR TITLE
Fix/inline linter rules to prevent conflict

### PR DESCRIPTION
**Pull request by mikedigit**
A fix for https://github.com/Earlybyte/aad_oauth/issues/275.

To prevent further issue of the sort I inlined the lint rules. The rules that were inlines are the rules of lints 3.0.0
Although this can add some extra work while upgrading the linting rules, it does set them in stone, and prevent further conflict as this package is getting more an more public attention.

I also took the extra steps to fix all the new lints rules. This translated in upgrading the example project to dart > 3.0.0, and minor modifications.

### CODE REVIEW

**Comment by loetsphi** [comment]
Hey @mikedigit 
That sounds reasonable, i actually introduced the lints package because the old linter package (pedantic) got deprecated.
I'll merge this as soon as you fix the remaining warnings.

Screenshot 2023-11-17 at 08 52 25

Thanks for your contribution.

**Comment by mikedigit** [comment]
Hey @loetsphi, it should be fine now.

As I wasnt 100% sure this package would be maintained, I made a fork of it with some changes for my project.
This fork introduces some change on error management on mobile-only, would you like me to introduce those change and possibly work out a MR from there ?

**Comment by loetsphi** [comment]
To keep it clean we only want the linter stuff in this MR, if you have additional changes please create another pull reequest, which we can review separately.
Can you provide a clean commit here with only the lints changes?

**Comment by mikedigit** [comment]
Sorry about the misunderstanding. 
This PR treats only about the lints changes, I did make several commits but all are related to this single purpose. 
You can definitely merge it safely.
If you wish I can definitely squash them into only one commit, but i'm not sure thats what you meant.

I was just broadening the conversation, but I understood your point. Other subjects will be treated in separate thread and a different MR. 👍

**Review by loetsphi — APPROVED** [review]

**Comment by loetsphi** [comment]
You were right, the merge commit doesn't matter. Sorry for the confusion... :) 
And thanks for the contribution!

**Pull request merged**
