### PR TITLE
Allow the configuring of a User Agent to be passed to the WebView

### PR DESCRIPTION
**Pull request by bradleybeighton**
Updated the auth webView to use the userAgent from the config.

This will enable users of the package to set a user agent which can then be passed through to the web view

### CODE REVIEW

**Comment by robaburgess** [comment]
That's great @bradleybeighton, hopefully it will be merged soon. @loetsphi any news on when this will be merged?

**Review by loetsphi — APPROVED** [review]

**Comment by loetsphi** [comment]
I merged it, and also exposed useragent in #75.
We'll wait with the release at least until #70 is merged.

**Comment by bradleybeighton** [comment]
@loetsphi thanks for merging! Is there a rough ETA on when the other PR will be merged? I am really relying on this piece of functionality. Is there any possibility of getting a minor release out before #70 is merged?

**Comment by loetsphi** [comment]
@bradleybeighton we would rather do the release properly. could you temporarly use aad_oauth directly from git instead of pub for the time being?

**Pull request merged**
